import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { clearOcrDraft, getOcrDraft, updateOcrDraftText } from "../services/captureDraftService";

export default function IngredientsReview() {
  const { id = "" } = useParams();
  const navigate = useNavigate();
  const draft = getOcrDraft(id);
  const [text, setText] = useState(draft?.result.rawText ?? "");
  if (!draft) return <main className="min-h-screen bg-slate-950 px-5 py-6 text-white"><section className="mx-auto max-w-md"><h1 className="text-2xl font-bold">Έλεγχος ετικέτας</h1><p className="mt-4 text-slate-300">Δεν βρέθηκε ανάγνωση ετικέτας.</p><button type="button" onClick={() => navigate("/scan")} className="mt-5 h-12 rounded-xl bg-emerald-500 px-5 font-bold text-slate-950">Νέα σάρωση</button></section></main>;
  const ocrDraft = draft;
  const nutritionOnly = ocrDraft.result.labelType === "nutrition";
  const insufficient = ocrDraft.result.labelType === "unknown" || text.trim().length < 12;
  function retake() { clearOcrDraft(id); navigate(`/ingredients-photo?barcode=${encodeURIComponent(ocrDraft.barcode)}`); }
  function confirm() { if (!text.trim() || nutritionOnly) return; updateOcrDraftText(id, text.trim()); navigate(`/product-photo?barcode=${encodeURIComponent(ocrDraft.barcode)}&productId=${encodeURIComponent(id)}`); }
  const label = ocrDraft.result.labelType === "ingredients" ? "Λίστα συστατικών" : ocrDraft.result.labelType === "nutrition" ? "Διατροφικός πίνακας" : ocrDraft.result.labelType === "mixed" ? "Μικτή ετικέτα" : "Άγνωστος τύπος";
  return <main className="min-h-screen bg-slate-950 px-4 py-5 text-white"><section className="mx-auto max-w-md"><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-400">Ανάγνωση ετικέτας</p><h1 className="mt-2 text-2xl font-bold">Έλεγχος κειμένου</h1><img src={ocrDraft.image} alt="Φωτογραφία ετικέτας συστατικών" className="mt-5 aspect-[3/4] w-full rounded-2xl border border-slate-700 object-cover" /><div className="mt-4 flex items-center justify-between rounded-xl bg-slate-900 p-4"><span className="font-semibold">{label}</span><span className="font-bold text-emerald-300">{Math.round(ocrDraft.result.confidence * 100)}%</span></div>{nutritionOnly && <p className="mt-3 rounded-xl border border-amber-400/40 bg-amber-400/10 p-3 text-sm text-amber-50">Εντοπίστηκε διατροφικός πίνακας, όχι λίστα συστατικών.</p>}{ocrDraft.result.labelType === "mixed" && <p className="mt-3 rounded-xl border border-amber-400/40 bg-amber-400/10 p-3 text-sm text-amber-50">Ελέγξτε ότι το κείμενο περιλαμβάνει ολόκληρη τη λίστα συστατικών.</p>}{insufficient && <p className="mt-3 rounded-xl border border-slate-700 bg-slate-900 p-3 text-sm text-slate-200">Δεν υπάρχουν αρκετά στοιχεία για αξιόπιστη ανάλυση.</p>}<label htmlFor="ocr-text" className="mt-5 block font-semibold">Κείμενο ετικέτας</label><textarea id="ocr-text" value={text} onChange={(event) => setText(event.target.value)} className="mt-2 min-h-40 w-full rounded-xl border border-slate-700 bg-slate-900 p-4 leading-6" />{ocrDraft.result.unreadableSegments.length > 0 && <p className="mt-3 text-sm text-slate-400">Μη αναγνώσιμα σημεία: {ocrDraft.result.unreadableSegments.join(", ")}</p>}<button type="button" onClick={confirm} disabled={!text.trim() || nutritionOnly} className="mt-6 h-14 w-full rounded-xl bg-emerald-500 font-bold text-slate-950 disabled:bg-slate-700">Επιβεβαίωση συστατικών</button><button type="button" onClick={retake} className="mt-3 h-12 w-full rounded-xl border border-slate-600 font-semibold">{nutritionOnly ? "Νέα φωτογραφία συστατικών" : "Λήψη φωτογραφίας ξανά"}</button></section></main>;
}